"""
Django settings for scat project.

Generated by 'django-admin startproject' using Django 3.0.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.0/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'ifs^e%o^c_!cu*!57#r@4fe0^9w#8r$ov=6@#2wl)c#8u6y#(t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'scat',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Scat.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Scat.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.0/howto/static-files/

STATIC_URL = '/static/'


DOWNLOAD_URL = 'localhost'
VERSION = 20171223
HALL_ATTR = 'localhost:10002'
ACCOUNT_PRI_KEY = '^&*#$%()@;'
TOKEN_PRI_KEY = ';@()%$#*&'

MASTER = {
    "root_host": "localhost",
    "root_port": 9999,
    "web_port": 9998
}

SERVERS = {
    'account': {
        'web_port': 10000,
        'db': True,
        'cache': True,
        'app': 'account',
        'log': 'logs/account.log',
        'remote_list': [
            {
                'root_port': 10001,
                'root_name': 'hall'
            }
        ],
    },
    'hall': {
        'name': 'texas_hall',
        'root_port': 10001,
        'web_port': 10002,
        'log': 'logs/hall.log',
        'app': 'hall',
        'db': True,
        'cache': True,
    },
    'game': {
        'name': 'game',
        'web_port': 10003,  # web_socket
        'server': 'servers.game_server',
        'log': 'logs/game.log',
        'db': True,
        'mem': True,
        'app': 'game',
        #'reload': 'app/game/reload',
        'remote_list': [
            {
                'root_port': 10001,
                'root_name': 'hall'
            }
        ],
    }
}

DB = {
    'host': 'localhost',
    'username': 'root',
    'password': 'root',
    'port': 3306,
    'db_name': 'texas',
    "charset": 'utf8'
}

CACHE = {
    'host': '127.0.0.1:6379',
    'port': 6379,
    'host_name': 'texas'
}